WorldBank:
  outputs:
    ci:
      dbname: postgres
      host: ${{ secrets.DB_HOST }}
      pass: ${{ secrets.DB_PASSWORD }}
      port: 5432
      schema: public
      threads: 2
      type: postgres
      user: ${{ secrets.DB_USER }}
  target: ci
