WorldBank:
  outputs:
    ci:
      dbname: postgres
      host: $DB_HOST
      pass: $DB_PASSWORD
      port: 5432
      schema: public
      threads: 2
      type: postgres
      user: $DB_USER
  target: ci
