WorldBank:
  outputs:
    ci:
      dbname: postgres
      host: 172.17.0.1
      pass: 1qaz2wsx@
      port: 5432
      schema: public
      threads: 2
      type: postgres
      user: postgres
  target: ci
