WorldBank:
  outputs:
    ci:
      dbname: postgres
      host: "{{ env_var('HOST') }}"
      pass: "{{ env_var('PASSWORD') }}"
      port: 5432
      schema: public
      threads: 2
      type: postgres
      user: "{{ env_var('USER') }}"
  target: ci
