name: dbt CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_HOST: ${{ secrets.DB_HOST }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.DB_USER }}" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt Core
        run: pip install dbt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run dbt deps
        run: dbt deps

      - name: Run dbt seed
        run: dbt seed --profiles-dir . --target ci

      - name: Run dbt run
        run: dbt run --profiles-dir . --target ci

      - name: Run dbt test
        run: dbt test --profiles-dir . --target ci
