name: dbt CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.2
        env:
          POSTGRES_HOST: 172.17.0.1
          POSTGRES_DB: "postgres"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: 1qaz2wsx@
        ports:
          - 5432:5432
        

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.8'


      - name: Install dependencies
        run: pip install -r requirements.txt
          

      - name: Run dbt build
        run: dbt build --profiles-dir . --target ci
